spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL:jdbc:mysql://127.0.0.1:3306/art?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEV_DB_USERNAME:root}
    password: ${DEV_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${DEV_JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    com.zaxxer.hikari: DEBUG
    com.mysql.cj: DEBUG
