spring:
  application:
    name: art-design-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/art?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "151505"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

jwt:
  secret: "change-me-to-a-strong-secret-32-bytes-minimum"
  expiration-seconds: 86400
